//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        [Required]
        public int PostId { get; set; }
        [Required]
        public string PostName { get; set; }
        [Required]
        public string PostContent { get; set; }
        [Required]
        public System.DateTime CreatedOn { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        
        public int BlogId { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
